openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description 
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /pets/{pet_id}:
    get:
      summary: Returns more info about a pet by its ID.
      description: Optional extended description.
      parameters:
        - name: pet_id
          in: path
          required: true
          description: The ID of the pet.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':    # status code
          description: information about a pet.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: The pet is invalid (not an integer).
        '404':
          description: A pet with the specified ID was not found.
        default:
          description: Unexpected error 