openapi: 3.0.0
info:
  title: Example Photo Service
  description: Optional multiline or single-line description 
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /playlists:
    get:
      summary: Returns a list of playlists
      description: list of playlists
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
        - name: offset
          in: query
          required: false
          type: integer
        - name: search
          in: query
          required: false
          type: string 
      responses:
        '200':    # status code
          description: list of playlists.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: The parameters have an invalid format.
        '404':
          description: No playlists were found.
        default:
          description: Unexpected error
  /playlists/{playlist_id}:
    delete:
      summary: Deletes a playlist by its ID.
      description: Optional extended description.
      parameters:
        - name: playlist_id
          in: path
          required: true
          description: The ID of the playlist.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':    # status code
          description: the playlist was deleted.
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: The playlist is invalid (not an integer).
        '404':
          description: A playist with the specified ID was not found.
        default:
          description: Unexpected error         