openapi: 3.0.0
info:
  title: Example Photo Service
  description: Optional multiline or single-line description 
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /playlists:
    get:
      summary: Returns a list of playlists
      description: list of playlists
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
        - name: search
          in: query
          required: false
          schema:
            type: string
            minLength: 1
      responses:
        '200':    # status code
          description: list of playlists.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '400':
          description: The parameters have an invalid format.
        '404':
          description: No playlists were found.
        default:
          description: Unexpected error
    post:
      summary: Creates a new playlist
      description: Optional extended description.
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                name:
                  type: string
                  minLength: 0
                  maxLength: 20
                genre:
                  type: string
                  minLength: 0
                  maxLength: 10
                duration_seconds:
                  type: integer
                  format: int32 
                  minimum: 1
                  maximum: 99999
                song_ids:
                  type: array
                  items:
                    type: integer
                    format: int64 # int64 - long
                created:
                  type: string
                  format: date # aaaa-mm-dd
                  minLength: 10
                  maxLength: 10
              required:
                - name
                - genre
                - created
      responses:
        '200':    # status code
          description: the playlist was created.
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: The information that was sent is invalid.
        default:
          description: Unexpected error 
  /playlists/{playlist_id}:
    delete:
      summary: Deletes a playlist by its ID.
      description: Optional extended description.
      parameters:
        - name: playlist_id
          in: path
          required: true
          description: The ID of the playlist.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':    # status code
          description: the playlist was deleted.
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: The playlist is invalid (not an integer).
        '404':
          description: A playist with the specified ID was not found.
        default:
          description: Unexpected error
    get:
      summary: Returns a playlist ny its ID
      description: playlist
      parameters:
        - name: playlist_id
          in: path
          required: true
          description: The ID of the playlist.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':    # status code
          description: information about the playlist
          content:
            application/json:
              schema:   
                type: object
                properties:
                  name:
                    type: string
                    minLength: 0
                    maxLength: 20
                  genre:
                    type: string
                    minLength: 0
                    maxLength: 10
                  duration_seconds:
                    type: integer
                    format: int32 
                    minimum: 1
                    maximum: 99999
                  song_ids:
                    type: array
                    items:
                      type: integer
                      format: int64 # int64 - long
                  created:
                    type: string
                    format: date # aaaa-mm-dd
                    minLength: 10
                    maxLength: 10
                required:
                  - name
                  - genre
                  - created
        '400':
          description: The parameters have an invalid format.
        '404':
          description: No playlists were found.
        default:
          description: Unexpected error            