openapi: 3.0.0
info:
  title: Serviço de gerenciamento de tarefas
  description: Gerencia tarefas e cadastros de usuários
  version: 0.1.9
servers:
  - url: http://api.gerenciame.com/v1 # SUGESTÃO NOME DA APLICAÇÃO
    description: Serviço de gerenciamento de tarefas e cadastros
paths:
  /cadastros:
    post:
      summary: Insere um novo cadastro na plataforma. Na base de dados, um novo id deve ser gerado a cada nova inserção.
      description: inserção de cadastros. É preciso que haja um select de e-mail na base de dados para que não sejam criados cadastros em duplicidade.
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                nome:
                  description: nome do usuário
                  type: string
                  minLength: 3
                  maxLength: 20
                sobrenome:
                  description: sobrenome do usuário
                  type: string
                  minLength: 3
                  maxLength: 50
                e-mail:
                  description: e-mail no formato usuario@email.com
                  type: string
                  minLength: 7
                  maxLength: 20
                  format: email
                senha:
                  description: senha do usuário
                  type: string
                  minLength: 6
                  maxLength: 100
                lgpd:
                  description: indicador que o usuário aceitou LGPD. Deve ser enviada sempre como "true"
                  type: boolean
              required:
                - nome
                - sobrenome
                - e-mail
                - senha
                - lgpd1
      responses:
        '200':    # status code
          description: o cadastro foi criado. Cada cadastro criado deverá gerar um id na base.
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: a requisição enviada possui algum item de tipagem diferente ou faltante e/ou o e-mail já existe na base de dados
        '500':
          description: erro no servidor

  /tarefas:
    post:
      summary: Insere uma nova tarefa na plataforma
      description: Inserção de uma nova tarefa no calendário. Na base de dados, novos ids de tarefas e subtarefas devem ser gerados.
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                nome_tarefa: 
                  description: nome da tarefa
                  type: string
                  minLength: 1
                  maxLength: 50
                data_inicial:
                  description: data inicial no formato aaaa-mm-dd, onde a atividade estará no calendário
                  type: string
                  pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                  minLength: 10
                  maxLength: 10
                data_limite:
                  description: data limite para finalizar a atividade no formato aaaa-mm-dd
                  type: string
                  pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                  minLength: 10
                  maxLength: 10
                hora:
                  description: horário no formato hh:mm, onde a tarefa deverá estar no calendário
                  type: string
                  minLength: 0
                  maxLength: 5
                  pattern: ^[0-2][0-3]:[0-5][0-9]$ # 00:00 a 23:59
                status:
                  description: porcentagem que aumenta conforme as subtarefas são finalizadas
                  type: integer
                  format: int32
                  minimum: 0
                  maximum: 100
                descricao:
                  description: descrição da atividade
                  type: string
                  minLength: 0
                  maxLength: 100
                subtarefas:
                  description: subtarefas necessárias para finalizar a atividade
                  type: array
                  items:
                    type: object
                    properties:
                      nome_subtarefa: 
                        description: nome da subtarefa
                        type: string
                        minLength: 0
                        maxLength: 200
                      anexo_subtarefa:
                        description: arquivo que o usuário quiser anexar
                        type: string 
                        format: url
                        minLength: 0 # caso não houver anexo, deixar vazio
                      status_subtarefa:
                        description: status da subtarefa
                        enum: [a fazer, fazendo, feito]
                        type: string
                        minLength: 5
                        maxLength: 7
              required:
                - nome_tarefa
                - data_inicial
                - data_limite
                - hora
                - status
                - subtarefas
      responses:
        '200':    # status code
          description: a atividade foi criada
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: a requisição enviada possui algum item de tipagem diferente ou faltante
        '500':
          description: erro no servidor
    get:
      summary: retorna uma lista de atividades
      description: lista de tarefas e subtarefas
      parameters:
      - name: data_inicio
        in: query
        required: true
        schema:
          description: data no formato aaaa-mm-dd. Range pode ser de no máximo 7 dias.
          type: string
          pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
          minLength: 10
          maxLength: 10
      - name: data_final
        in: query
        required: true
        schema:
          description: data no formato aaaa-mm-dd. Range pode ser de no máximo 7 dias.
          type: string
          pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
          minLength: 10
          maxLength: 10
      responses:
        '200':    # status code
          description: a pesquisa retornou resultados com sucesso
          content:
            application/json:
              schema: 
                type: object
                properties:
                  tarefas:
                    type: array
                    items:
                      type: object
                      properties: 
                        id_tarefa:
                          description: id da atividade
                          type: integer
                          format: int32 
                          minimum: 1
                          maximum: 2147483647
                        nome_tarefa: 
                          description: nome da tarefa
                          type: string
                          minLength: 1
                          maxLength: 50
                        data_inicial:
                          description: data inicial no formato aaaa-mm-dd, onde a atividade estará no calendário
                          type: string
                          pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                          minLength: 10
                          maxLength: 10
                        data_limite:
                          description: data limite para finalizar a atividade no formato aaaa-mm-dd
                          type: string
                          pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                          minLength: 10
                          maxLength: 10
                        hora:
                          description: horário no formato hh:mm, onde a tarefa deverá estar no calendário
                          type: string
                          minLength: 0
                          maxLength: 5
                          pattern: ^[0-2][0-3]:[0-5][0-9]$ # 00:00 a 23:59
                        descricao:
                          description: descrição da atividade
                          type: string
                          minLength: 0
                          maxLength: 100
                        subtarefas:
                          description: subtarefas necessárias para finalizar a atividade
                          type: array
                          items:
                            type: object
                            properties:
                              id_subtarefa:
                                description: id da subtarefa
                                type: integer
                                format: int32 
                                minimum: 1
                                maximum: 2147483647
                              nome_subtarefa: 
                                description: nome da subtarefa
                                type: string
                                minLength: 0
                                maxLength: 200
                              anexo_subtarefa:
                                description: arquivo que o usuário quiser anexar
                                type: string 
                                format: url
                                minLength: 0 # caso não houver anexo, deixar vazio
                              status_subtarefa:
                                description: status da subtarefa
                                enum: [a fazer, fazendo, feito]
                                type: string
                                minLength: 5
                                maxLength: 7
        '400':
          description: a requisição enviada possui algum item de tipagem diferente ou faltante
        '500':
          description: erro no servidor
  /tarefas/{id_tarefa}:          
    patch:
      summary: realiza a edição de uma atividade
      description: edita um ou mais campos de uma tarefa. O campo status não pode ser editado, ele deve ser calculado mediante a existência e status das subtarefas.
      parameters:
      - name: id_tarefa
        in: path
        required: true
        schema:
          description: id da atividade
          type: integer
          format: int32 
          minimum: 1
          maximum: 2147483647
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                nome_tarefa: 
                      description: nome da tarefa
                      type: string
                      minLength: 1
                      maxLength: 50
                data_inicial:
                  description: data inicial no formato aaaa-mm-dd, onde a atividade estará no calendário
                  type: string
                  pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                  minLength: 10
                  maxLength: 10
                data_limite:
                  description: data limite para finalizar a atividade no formato aaaa-mm-dd
                  type: string
                  pattern: ^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$
                  minLength: 10
                  maxLength: 10
                hora:
                  description: horário no formato hh:mm, onde a tarefa deverá estar no calendário
                  type: string
                  minLength: 0
                  maxLength: 5
                  pattern: ^[0-2][0-3]:[0-5][0-9]$ # 00:00 a 23:59
                descricao:
                  description: descrição da atividade
                  type: string
                  minLength: 0
                  maxLength: 100
                subtarefas:
                  description: subtarefas necessárias para finalizar a atividade
                  type: array
                  items:
                    type: object
                    properties:
                      id_subtarefa:
                        description: id da subtarefa
                        type: integer
                        format: int32 
                        minimum: 1
                        maximum: 2147483647
                      nome_subtarefa: 
                        description: nome da subtarefa
                        type: string
                        minLength: 0
                        maxLength: 200
                      anexo_subtarefa:
                        description: arquivo que o usuário quiser anexar
                        type: string 
                        format: url
                        minLength: 0 # caso não houver anexo, deixar vazio
                      status_subtarefa:
                        description: status da subtarefa
                        enum: [a fazer, fazendo, feito]
                        type: string
                        minLength: 5
                        maxLength: 7
      responses:
        '200':    # status code
          description: a edição ocorreu com sucesso
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: a requisição enviada possui algum item de tipagem diferente ou faltante
        '500':
          description: erro no servidor
    delete:
      summary: deleta uma tarefa
      description: deleção de tarefa
      parameters:
      - name: id_tarefa
        in: path
        required: true
        schema:
          description: id da atividade
          type: integer
          format: int32 
          minimum: 1
          maximum: 2147483647
      responses:
        '200':    # status code
          description: a deleção ocorreu com sucesso
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: a requisição enviada possui algum item de tipagem diferente ou faltante
        '500':
          description: erro no servidor
  /tarefas/{id_tarefa}/subtarefas/{id_subtarefa}: 
    delete:
      summary: deleta uma subtarefa
      description: playlist
      parameters:
      - name: id_tarefa
        in: path
        required: true
        schema:
          description: id da atividade
          type: integer
          format: int32 
          minimum: 1
          maximum: 2147483647
      - name: id_subtarefa
        in: path
        required: true
        schema:
          description: id da subtarefa
          type: integer
          format: int32 
          minimum: 1
          maximum: 2147483647
      responses:
        '200':    # status code
          description: a deleção ocorreu com sucesso
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: a requisição enviada possui algum item de tipagem diferente ou faltante
        '500':
          description: erro no servidor
         
